### ISSUE TITLE
Label graphs on https://sourcemeta.github.io/json-size-benchmark/ with "Size" on the Y axis

### ISSUE THREAD

**Issue by zellyn** [jviotti/jsonbinpack#161]
I guess I'm feeling dumb now, but I had to click through to the paper and scroll down until I found a similar-looking (but with labels!) graph to understand what exactly I was looking at.

I also think it would be useful to put data size explicitly on that page. I understood what numeric and redundant meant, but had to actually click through and read the Tier definitions in the JSON Taxonomy Project.

But, *very* nice. I am so happy to find this benchmark study!

**Comment by jviotti** [comment]
Extremely great suggestions. Thanks a lot for sharing them! I'll aim for implementing them during the weekend.

**Comment by jviotti** [comment]
All set! The updates should be deployed to the site pretty soon. I'll go ahead and close this issue, but do let me know what you think and if you have any other suggestions!
